---

- name: Run the Fedora based install
  include: "Fedora.yml"
  when: ansible_distribution == "Fedora"

- name: Run the RedHat based install
  include: "RHEL.yml"
  when: ansible_distribution != "Fedora"
