---

- name: install yum repo
  copy:
    owner=root
    src=files/docker.repo
    dest=/etc/yum.repos.d/docker.repo

- name: Install docker
  yum: name=docker-engine state=present

- name: making sure pip installed
  shell: which pip || curl -sSL https://bootstrap.pypa.io/get-pip.py | python

- name: Install docker-compose
  pip: name=docker-compose state=present

- name: Install docker-py
  pip: name=docker-py version=1.8.1 state=forcereinstall
